### ISSUE TITLE
error when install in atom

### ISSUE THREAD

**Issue by msalcantara** [AtomLinter/linter-pylama#113]
I install pylma in atom, and when I save .py file I got this error:

```Traceback (most recent call last): File "/home/matheus/.atom/packages/linter-pylama/bin/pylama.py", line 12, in from pylama.main import shell File "/home/matheus/.atom/packages/linter-pylama/bin/pylama/main.py", line 10 from .async import check_async ^ SyntaxError: invalid syntax```

What happen??
I'm usigin python 3.7.2

`$ python -V `
`$ Python 3.7.3`

**Comment by gmist** [comment]
> What happen??

You're using Python 3.7

**Comment by msalcantara** [comment]
this linter not work with python 3.7?

**Comment by msalcantara** [comment]
maybe should be useful add in readme the python version requirements

**Comment by Arcanemagus** [comment]
This works perfectly fine in Python 3.7, you just need to go into the settings and change it to use `External` for the version of Pylama. Make sure that Pylama has been installed on your system first before switching to that.

The customized bundled version of `pylama` is unfortunately the problem here, not the integration itself.

**Comment by Arcanemagus** [comment]
Looks like this is actually a duplicate issue.

**Comment by Arcanemagus** [comment]
Duplicate of #102
