### ISSUE TITLE
Please fix pylama path or install latest version.

### ISSUE THREAD

**Issue by xiaoxiaojuan** [AtomLinter/linter-pylama#78]
a lot of this message keep showing up, no matter I uninstall or disable or give a correct pylama's path.

**Comment by gmist** [comment]
A little more details, please
What OS is used??
Atom version (`atom --version`)?
Python version (`python -V; which python`)?
Pylama version (`pylama --version; which pylama`)?
Virtualenv is used?

**Comment by xiaoxiaojuan** [comment]
1. OS version:
2.Atom version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
3.python
Python 2.7.13
/usr/local/bin/python
4.Pylama version
pylama 7.3.3
/usr/local/bin/pylama
5. virtualenv is not used

**Comment by KayJay89** [comment]
I concur with the above. I have witnessed the same problems. No matter what you do, uninstall, reinstall, disable it,.. the popup appears. One would think that this would not show up if the package was not even installed to begin with.

1.OS: Windows 10 Pro
2.Atom 1.18
3.Python 3.6.1
4.Pylama version 0.9.3
5.virtualenv not used

**Comment by hawksight** [comment]
Seems similar issue been around a while: https://github.com/AtomLinter/linter-pylama/issues/6

I have the same error as @JohnRobson 
MacOS Sierra 10.12.5

➜  ~ apm list --installed --bare
busy-signal@1.4.3
git-blame@1.1.1
intentions@1.1.2
language-elixir@0.19.0
language-erlang@3.2.0
linter@2.2.0
linter-pylama@0.9.3
linter-python@3.1.2
linter-ui-default@1.6.2
minimap@4.28.2
python-indent@1.0.3
split-diff@1.4.3

pip list
pylama                             7.4.1
pylama-pylint                      3.0.1
pylint                             1.7.2
(+ a whole load more)

In virtual env - python3: pip3 list
pylama            7.4.1
pylama-pylint     3.0.1
pylint            1.7.2
(+ a whole load more)

Full paths under - Atom -> Preferences -> packages -> Linter Pylama -> Settings
Still every time I hit save or load up atom, get the little message.
"Provided path doesn't exist.
pylama
Please fix pylama path or install latest version"

I previously uninstalled it all due to this message popping up constantly. Fresh install hasn't fixed it.

**Comment by gmist** [comment]
@hawksight  [it looks](https://github.com/pchomik/linter-python/blob/master/lib/linter.js#L50) like a conflict with ```linter-python```, try to uninstall ```linter-python``` or ```linter-pyjama```

**Comment by richardham** [comment]
@xiaoxiaojuan
I got same message that "provided path doesn't exist ...". OS is Ubuntu16.04.
Maybe we have to set path to pylama binary. /usr/local/bin/pylama →  /usr/bin/pylama
I typed "cp /usr/local/bin/pylama /usr/bin/", then linter-python worked.

**Comment by gmist** [comment]
@richardham you just need to change the path in ```linter-python``` settings. In general ```linter-pyjama``` and ```linter-python``` have similar functionality so you do not need to install them together - leave only one of them at your choice.

**Comment by richardham** [comment]
@gmist Thank you. I changed settings then linter-python worked.

**Comment by xiaoxiaojuan** [comment]
@gmist I uninstall my linter-python, it works, thank you

**Comment by gmist** [comment]
Nice!

**Comment by hawksight** [comment]
Thanks @gmist - that worked a treat.
Just for anyone else who has issues, mine works now with:
apm list
├── linter-python@3.1.2

pip list
pylama                             7.4.1

and in settings for linter-python, path set to: /usr/local/bin/pylama

**Comment by damianobarbati** [comment]
Not working with `linter-python@3.1.2`.
I have pylama at `/usr/local/bin/pylama` which is the default location but linter-pylama does not find either way: not if I leave the default path, neither if I set it (uselessly?) manually to `/usr/local/bin/pylama`.

Error message:
```
Provided path doesn't exist.
/usr/local/bin/pylama
Please fix pylama path or install latest version
```
Double check existence in console:
```
imac:core damz$ which pylama
/usr/local/bin/pylama
```

Any idea?

**Comment by gmist** [comment]
@damianobarbati, this message was received from ```linter-python``` not from ```linter-pylama```. Unfortunately these plugins conflict because both do the same thing. You need to choose one of them.

**Comment by AjayJohnAlex** [comment]
[Linter] Error running Flake8 Error: Process execution timed out ....
how can i resolve this error??

**Comment by dimkoug** [comment]
for ubuntu 18 
sudo apt install pylama

then to find pylama path enter the command

which pylama

then copy the path in linter-python package in executable path

**Comment by AaronZhangL** [comment]
In my case, Pylama was installed here:
/Users/{your-user-id}/.pyenv/versions/anaconda3-5.3.1/envs/anac3-5.3.1/lib/python3.7/site-packages/pylama
I added this path to [Executable path for external Pylama] and it worked.
